### ISSUE TITLE
How to generate js code for custom blocks?

### ISSUE THREAD

**Issue by prateek756** [roroettg/ngx-blockly#15]
I am using ngx-blockly for my project and I have created **custom blocks**, which is working fine but now I want to generate the **JavaScript code** from the xml which has been created by my custom blocks. Or there is any event for directly getting the js code for custom blocks like we are getting for predefined blocks by **(javascriptCode)** event. Please help me, I got stuck here.

**Comment by roroettg** [comment]
Hi, 
you can overwrite following methods from CustomBlocks in your subclass to achieve code generation for your custom blocks:

```
    public toDartCode(block: CustomBlock): string | any[] {
        return 'Not implemented';
    }

    public toJavaScriptCode(block: CustomBlock): string | any[] {
        return 'Not implemented';
    }

    public toLuaCode(block: CustomBlock): string | any[] {
        return 'Not implemented';
    }

    public toPHPCode(block: CustomBlock): string | any[] {
        return 'Not implemented';
    }

    public toPythonCode(block: CustomBlock): string | any[] {
        return 'Not implemented';
    }
```

**Comment by prateek756** [comment]
Hi, 

Thanks for the response but from where these methods will be called, Like I want to call **toJavaScriptCode()** then from where I have to call this method? 

And if it is possible to send any example of code generation for JS then please do. It will be very helpful for me to understand the code generation for custom block.

**Comment by roroettg** [comment]
Usually you will not be calling the method yourself, since generation is triggered when changes to the workspace occur, e.g. Block creation or movement.

As you can see in the code generation example (https://github.com/roroettg/ngx-blockly#code-generation), that you need to activate javascript generation through the **javascript flag** in NgxBlocklyGeneratorConfig. After that you will receive javascript code on workspace changes through the **javascriptCode** output binding.

```
public generatorConfig: NgxBlocklyGeneratorConfig = {
        javascript: true
    };
```

```
<ngx-blockly [config]="config" [generatorConfig]="generatorConfig" (javascriptCode)="onCode($event)" ></ngx-blockly>
```

**Comment by roroettg** [comment]
Issue seems solved.

**Comment by fjaen** [comment]
Hello, I am also having a problem with this. I have in my app.component.html:

<div><p>{{generatedcode}}</p></div>
<div class="container">
  <ngx-blockly [config]="config" [generatorConfig]="generatorConfig" (javascriptCode)="onCode($event)" ></ngx-blockly>
</div>

but it seems my onCode method is not called because no text code is displayed when I drop blocks in the workspace

constructor() {
  this.generatedcode="Code displayed here";
 }

onCode(code: string) {
    this.generatedcode=code
}
Please, could you help me with this problem? 
Thanks

**Comment by fjaen** [comment]
I solved the issue. I had to add
"node_modules/ngx-blockly/scripts/blockly/javascript_compressed.js",
to the scripts in angular.json
