### ISSUE TITLE
goog is not defined

### ISSUE THREAD

**Issue by evdigitech** [roroettg/ngx-blockly#21]
When I am using 
"**var htmlInput = goog.dom.createDom(goog.dom.TagName.INPUT, 'blocklyHtmlInput')**" 
in my project then I am getting error :
**goog is not defined**

How can I define **goog**, So I will not get this error?

**Comment by roroettg** [comment]
Not really sure what you are trying to achieve, please provide more input.

I am guessing you are trying to implement custom fields?
Maybe this issue helps you https://github.com/roroettg/ngx-blockly/issues/8

**Comment by evdigitech** [comment]
See, I am trying to add datalist to input in my project, so I am following this link: 
[https://groups.google.com/forum/#!topic/blockly/XBS1RIc5EHA]
Please visit this link, so you can understand it better. 
I am asking this question here because I am using ngx-blockly in my project. Please let me know if you have any idea about this.

**Comment by roroettg** [comment]
Ok, in the issue I posted @dpasdar tried to achieve the same feature. I don't know if he found a way to achieve it, maybe you can contact him.

Otherwise the example i posted, shows you a way to implement custom fields, like you are trying to do. You should probably be able to adapt the code from the google groups without goog.

I am not sure if you can use goog in angular environments and cannot help you on this part.

**Comment by evdigitech** [comment]
Ok, Thanks. I will take reference of the issue that you had shared.

**Comment by roroettg** [comment]
Seems resolved.
