### ISSUE TITLE
How to upgrade to latest version?

### ISSUE THREAD

**Issue by evdigitech** [roroettg/ngx-blockly#34]
Hi, 

I am using ngx-blockly of version 0.0.45 and I want to upgrade it to latest version. I can install the latest version but my concern is that is there anything which will be break after upgrading to latest version because I have used many blocks in current version. Please suggest the best way to upgrade.

Thanks

**Comment by roroettg** [comment]
Hi,

0.0.45 is more than a year old, which makes it pretty hard to make an estimation what can break without knowing your project.

Following changes could break your code:
- Blockly itself received updates
- Newer Angular version
- Wrapper updates

The wrapper updates mostly implemented new features and might not be biggest threat.

My suggestion for your code would be to update to Angular 10, since the library is currently only build against 10 (the major number is an indicator for the angular version), and try to update to the latest ngx-blockly version. If your custom-blocks aren't too fancy there might not be too much issues.

If you run into issues you cannot solve, feel free to ask here.
