### ISSUE TITLE
Accessing statement blocks of an input

### ISSUE THREAD

**Issue by fjaen** [roroettg/ngx-blockly#44]
Hi,
I have a custom block that has a statement input named "UPDATE_SCRIPT". How could I access all the statements that have been inserted in this input?

I  tried something like 

toLuaCode(block: CustomBlock): string | any[] {
...
        let child_block=block.block.getInputTargetBlock('UPDATE_SCRIPT');
        
        if(child_block)
        do{
            // do something here with each statement block that was inserted in the statement input
        }while (child_block = child_block.getNextBlock());
...
}
but I get an error TypeError: Cannot read property 'getInputTargetBlock' of undefined
Thank you very much for your help.

**Comment by roroettg** [comment]
Hi,
I fear this part is a bit confusing and not very clean.

You are able to use getInputTargetBlock by `block.getInputTargetBlock(name)`. This will probably lead to a compilation error if you just use it like this, since getInputTargetBlock is not defined on CustomBlock..

I would suggest sth. like this.

```
toLuaCode(block: any): string | any[] {
  let child_block = block.getInputTargetBlock('UPDATE_SCRIPT');
  if(child_block)
    do{
        // do something here with each statement block that was inserted in the statement input
    }while (child_block = child_block.getNextBlock());
}
```

**Comment by fjaen** [comment]
Thank you very much! This solved the issue.
