### ISSUE TITLE
Option `defaultBlocks` is completely useless.

### ISSUE THREAD

**Issue by Char2sGu** [roroettg/ngx-blockly#84]
Hi!
I found that there are no handlers for the `defaultBlocks` options in this library, and it seems that I have to import `blockly/blocks` manually to use the default blocks?

**Comment by roroettg** [comment]
Hi,
yes you are completely right. I was working on this, but could not find a working solution yet, since the default blocks have to be imported at a very early stage. Unfortunately I forgot about this flag. 

But thank you for reminding me about this. I had some time today and was able to find a solution, which I will commit within in the next days.
